### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by jinyuyuyu** [ChronoBro/NuclearSims#1]
Hi,

I'm Yu from Peking University. We are doing some research related to 2p decay. I have some questions about the simulation code and I hope to get some answers from you.

1) In decay.cpp, I see you have the Moscow theoretical input in the CDecay class. it's Moscow = new moscow("6be_p2_new.dat"), then you use the ModeMoscow() function by which Moscow->getEvernt(), where you get each line from the input file:
     ifFile >> Etot
     >> p1[0] >> p1[1] >> p1[2]
     >> p2[0] >> p2[1] >> p2[2]
     >> p3[0] >> p3[1] >> p3[2]; 
But I don't know what the variable Etot represents here. Is it a constant or have you considered the decay width to let it be a BreitWigner random number? Could please let me know the input file format? It would be best if you can send me the input file "6be_p2_new.dat".

2) I also noticed some constants in this code. In deay.cpp, you use 0.9784 when you calculate kinetic energy from velocity. In moscow.cpp, you use sqrt(979.82) when you calculate velocity from momentum. Could you please explain why you use these constants and how to get them?

Thank you! You can contact me by email: yuu@pku.edu.cn.

**Comment by ChronoBro** [comment]
Hi Yu,

- Unfortunately I do not have the "6be\_p2\_new.dat" file anymore. What I can tell you is that this was a file with the momentum distribution of the relevant fragments created in knockout reactions, calculated by [MOMDIS](http://cpc.cs.qub.ac.uk/summaries/ADXZ_v1_0.html). The momentum spread of the fragments will affect the overall invariant mass resolution.

- I apologize for the confusing constants. These were leftover from when I obtained the code and I haven't gotten around to making them more clear. All of the masses are normalized to nucleon mass ($`A = 939 \text{MeV}/c^2`$), velocities are given in cm/ns, and energies are in MeV.  If you calculate the velocity of fragment from newtonian mechanics and factor out all of the units you get, 
   ```math
    v = sqrt{2E/m}\times sqrt{A}\times MeV/A.
    ```

    The factor of units comes out to be 0.9784 cm/ns, and this is why that constant appears in the code.

**Comment by jinyuyuyu** [comment]
Thank you so much for your prompt reply!

 * Are you sure the "6be_p2_new.dat" file was calculated for knockout reaction by MOMDIS? Because I thought it might be calculated by Grigorenko in Dubna to obtain fragments' momenta in two-proton decay. I wish you could help me confirm this question.

Thank you!

**Comment by ChronoBro** [comment]
Hi Yu,

I think you may be right about "6be_p2_new.dat" actually. It's been a while since I've used the code and I may have misremembered what that file does. To be honest, I have not used any of the "moscow" decay modes, but I wanted to leave everything that I was given in the code in case someone else wanted to use it. Sorry I can't be more helpful.
